# Generated by Django 5.0.2 on 2024-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_bloc_alter_client_old_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bloc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='D/B'),
        ),
        migrations.AlterField(
            model_name='client',
            name='old_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Köne nomer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Otag'),
        ),
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hyzmat'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
    ]
