# Generated by Django 5.0.2 on 2024-03-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_customuser_useretrap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useretrap',
            options={'verbose_name': 'Ulanyjynyň degişli etraby', 'verbose_name_plural': 'Ulanyjynyň degişli etraby'},
        ),
    ]
