# Generated by Django 5.0.2 on 2024-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_useretrap_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='house',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Jaý'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Köçe'),
        ),
    ]
