# Generated by Django 5.0.2 on 2024-03-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_house_alter_client_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etrap',
            old_name='etrap_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='etrap',
            old_name='etrap_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='etrap',
            unique_together={('name', 'parent')},
        ),
    ]
